name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build the project
        run: cargo build --release

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: leetpw
          path: target/release/leetpw

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/leetpw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
